[package]
name = "cet-class-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
cet-class = { path = "../class" }

[dependencies.syn]
version = "1.0"
features = ["full"]
